<a href="https://colab.research.google.com/github/eliastche/PythonLabs/blob/main/cf_python_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercice 1** \
Write a Python program that:
* Asks the user to input the daily return of stocks (as percentage)
* Prints:
  * "Profit" if the return is positive
  * "Loss" if the return is negative
  * "No change" if its exactly zero
* With the additional conditions:
  * If the return is greater than 2%, print "Strong gain" instead
  * If the return is less than -2%, print "Strong loss" instead

In [ ]:
def dailyreturns():
  returnstock = float(input("Input the daily return of a stock in precentage: "))
  returnresult = "No change"

  if returnstock > 0:
    returnresult = "Profit"
  elif returnstock < 0:
    returnresult = "Loss"

  return print("The stock has", returnresult)

dailyreturns()

Input the daily return of a stock in precentage: 1.5
The stock has Profit

In [ ]:
#With additional constraints

def dailyreturns():
  returnstock = float(input("Input the daily return of a stock in precentage: "))
  returnresult = "No change"

  if 0 < returnstock <= 2:
    returnresult = "Profit"
  elif -2 <=returnstock < 0:
    returnresult = "Loss"
  elif 2 < returnstock:
    returnresult = "Strong gain"
  elif returnstock < -2:
    returnresult = "Strong loss"

  return print("The stock has", returnresult)

dailyreturns()

Input the daily return of a stock in precentage: 2.5
The stock has Strong gain

**Excercise 2**\
Write a python script that simulates the growth of an investment over several years
* Start with an initital capital of 1000
* For each year from 1 to 5, assume a 5% annual return
* Use a for loop to compute and print the capital at the end of each year liks:
  * Year 1: 1050€
  * Year 2: 1102.5€
  * ...
* After the loop print the total gain (final - initial)

In [ ]:
def growthinvestment(S0):
  r = 0.05
  years = [1,2,3,4,5]
  S = S0

  for y in years:
    S = S*(1+r)
    print(f"Year {y}: {S}€")

  gain = S-S0

  print(f"The total gain is: {gain}€")

growthinvestment(1000)

Year 1: 1050.0€
Year 2: 1102.5€
Year 3: 1157.625€
Year 4: 1215.5062500000001€
Year 5: 1276.2815625000003€
The total gain is: 276.2815625000003€

##Part 2: Data analysis and manipulation
**1. Load some stocks information into a pandas DataFrame**
* Using the yFinance module, use this code o download stock information from Apple, Microsoft and the S&P 500 index

In [2]:
!pip install yfinance
import yfinance as yf
tickers = ['AAPL', 'MSFT', '^GSPC']
df = yf.download(tickers, start='2018-01-01')

aapl_stock = df.xs('AAPL', level = 1, axis = 1)
msft_stock = df.xs('MSFT', level = 1, axis = 1)
gspc_stock = df.xs('^GSPC', level = 1, axis = 1)

aapl_stock.columns

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.10.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

/tmp/ipython-input-226361737.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, start='2018-01-01')
[*********************100%***********************]  3 of 3 completed

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='object', name='Price')

**a. Compute the returns of the 'Close' column and inspect the new dataframe**

In [3]:
aapl_stock['Return'] = aapl_stock['Close'].pct_change()
msft_stock['Return'] = msft_stock['Close'].pct_change()
gspc_stock['Return'] = gspc_stock['Close'].pct_change()

aapl_stock['Return'].head()

/tmp/ipython-input-3439504912.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aapl_stock['Return'] = aapl_stock['Close'].pct_change()
/tmp/ipython-input-3439504912.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msft_stock['Return'] = msft_stock['Close'].pct_change()
/tmp/ipython-input-3439504912.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gspc_stock['Return'] = gspc_stock['Close'].pct_change()

Date
2018-01-02         NaN
2018-01-03   -0.000174
2018-01-04    0.004645
2018-01-05    0.011385
2018-01-08   -0.003714
Name: Return, dtype: float64

**b. Compute the correlation of the returns of AAPL and MSFT with S&P 500**

In [6]:
!pip install pandas
import pandas as pd

merge_aapl_gspc = pd.merge(left=aapl_stock['Return'], right=gspc_stock['Return'], left_index=True, right_index=True, suffixes=('_sufx1', '_sufx2'))
merge_msft_gspc = pd.merge(left=msft_stock['Return'], right=gspc_stock['Return'], left_index=True, right_index=True, suffixes=('_sufx1', '_sufx2'))

merge_aapl_gspc = merge_aapl_gspc.dropna()
merge_msft_gspc = merge_msft_gspc.dropna()

#The correlations
aapl_gspc_corr = merge_aapl_gspc[['Return_sufx1', 'Return_sufx2']].corr()
msft_gspc_corr = merge_msft_gspc[['Return_sufx1', 'Return_sufx2']].corr()

print("Correlation between Apple and the S&P 500", aapl_gspc_corr)
print("Correlation between Microsoft and the S&P 500", msft_gspc_corr)

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Correlation between Apple and the S&P 500               Return_sufx1  Return_sufx2
Return_sufx1      1.000000      0.774971
Return_sufx2      0.774971      1.000000
Correlation between Microsoft and the S&P 500               Return_sufx1  Return_sufx2
Return_sufx1      1.000000      0.816218
Return_sufx2      0.816218      1.000000

**c. Compute the cumulative returns by calculating the cumulative product over the returns. Store the results in a new dataframe, and plot it by calling the pandas plot function**

In [10]:
import numpy as np

aapl_stock['cumu_return'] = np.cumprod(aapl_stock['Return']+1)
msft_stock['cumu_return'] = np.cumprod(msft_stock['Return']+1)
gspc_stock['cumu_return'] = np.cumprod(gspc_stock['Return']+1)

gspc_stock['cumu_return'].head()

/tmp/ipython-input-3340459767.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aapl_stock['cumu_return'] = np.cumprod(aapl_stock['Return']+1)
/tmp/ipython-input-3340459767.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msft_stock['cumu_return'] = np.cumprod(msft_stock['Return']+1)
/tmp/ipython-input-3340459767.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gspc_stock['cumu_return'] = np.cumprod(gspc_stock['Return']+1)

Date
2018-01-02         NaN
2018-01-03    1.006399
2018-01-04    1.010453
2018-01-05    1.017561
2018-01-08    1.019252
Name: cumu_return, dtype: float64

**d. Compute the annual returns assuming that there are 253 trading days per year**

In [11]:
aapl_stock['Annual Return'] = np.mean(aapl_stock['Return'])*252
msft_stock['Annual Return'] = np.mean(msft_stock['Return'])*252
gspc_stock['Annual Return'] = np.mean(gspc_stock['Return'])*252

aapl_stock.head()

/tmp/ipython-input-1973892047.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aapl_stock['Annual Return'] = np.mean(aapl_stock['Return'])*252
/tmp/ipython-input-1973892047.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msft_stock['Annual Return'] = np.mean(msft_stock['Return'])*252
/tmp/ipython-input-1973892047.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gspc_stock['Annual Return'] = np.mean(gspc_stock['Return'])*252

Price,Close,High,Low,Open,Volume,Return,cumu_return,Annual Return
Date,,,,,,,,
2018-01-02,40.341877,40.351247,39.639302,39.850076,102223600,NaN,NaN,0.288698
2018-01-03,40.334866,40.878192,40.271636,40.405124,118071600,-0.000174,0.999826,0.288698
2018-01-04,40.522221,40.625266,40.299739,40.407465,89738400,0.004645,1.004470,0.288698
2018-01-05,40.983570,41.070220,40.526897,40.618231,94640000,0.011385,1.015906,0.288698
2018-01-08,40.831356,41.126437,40.732992,40.831356,82271200,-0.003714,1.012133,0.288698